### ISSUE TITLE
Accept fasta files where the lines have different length

### ISSUE THREAD

**Issue by Unaimend** [kerrycobb/nim-dna-seq#2]
At the moment your implementation seems to be focused on alignment specific stuff but even then would it make sense to allow the fasta records to have different length?

**Comment by kerrycobb** [comment]
I think they all need to be the same length for an alignment. For example if you have:

ATGCATGC
GCATGC

Instead of
ATGCATGC
--GCATGC

They aren't aligned anymore and should be read as a list of sequences instead. In order to be an alignment you would need to run an algorithm that would add the -- to the beginning of the second sequence. 

The phylip format has the number of sites at the beginning of the file for this reason. 

But Fasta can contain a sequence list so there should at least be a proc for reading those into a list. I don't know enough about Nim yet to know if you could write a proc that would output one of two types based on the contents of a file.

**Comment by Unaimend** [comment]
Ok, that makes sense to have this kind of distinction, I will work on that
